# Generated by Django 5.1.4 on 2024-12-21 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.PositiveIntegerField()),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
                ('document', models.FileField(upload_to='contracts/')),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessee_contracts', to=settings.AUTH_USER_MODEL)),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessor_contracts', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upfront', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_details', to='leasing.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='leasing.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(choices=[('LR', 'Lessor'), ('LE', 'Lessee'), ('SE', 'Seller'), ('AD', 'Admin')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_cases', to='leasing.contract')),
            ],
        ),
    ]
