# Generated by Django 5.1.4 on 2024-12-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_remove_contract_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='ended',
        ),
    ]
