# Generated by Django 5.1.4 on 2024-12-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_remove_contract_ended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date']},
        ),
    ]
