# Generated by Django 5.1.4 on 2024-12-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0004_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='meter',
            field=models.CharField(max_length=20),
        ),
    ]
