# Generated by Django 5.1.4 on 2024-12-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_alter_contract_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantycase',
            name='resolved',
            field=models.CharField(choices=[('CR', 'Создан'), ('IW', 'В процесссе'), ('CO', 'Решен')], default='CR', max_length=2),
        ),
    ]
