# Generated by Django 5.1.4 on 2024-12-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_alter_warrantycase_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.CharField(default=10, max_length=30),
            preserve_default=False,
        ),
    ]
