# Generated by Django 5.1.4 on 2024-12-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0007_contract_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-started']},
        ),
    ]
