# Generated by Django 5.1.4 on 2024-12-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_alter_contract_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-started', '-number']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.CharField(choices=[('F', 'Не оплачен'), ('R', 'Запрос'), ('T', 'Оплачен')], default='F', max_length=1),
        ),
    ]
