# Generated by Django 5.1.5 on 2025-01-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0009_alter_contract_options_alter_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='request_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
